### ISSUE TITLE
noVNC Auth fail

### ISSUE THREAD

**Issue by newcanopies** [swilcock0/ros2_docker#1]
Hello, I was curious to test this implementation of noVNC but came across an authentication error. 
![image](https://user-images.githubusercontent.com/65022111/121589539-76330800-ca37-11eb-92d4-cd18a2713e14.png)

the password found in the Docker file does not work. Have you come across this before?

**Comment by swilcock0** [comment]
Sorry this is super delayed, had other work away from programming. I'm trying to get this container back up and running fully, after a bit of messing about it's working again now and upgraded to ROS2 Galactic (although only for vnc connections via the browser and not through port 5901).
